# Permalinks
permalink:           pretty

# Setup
title:               Jess DeJong
tagline:             My personal website
url:                 http://jessdejong.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jess DeJong
  url:               https://github.com/jessdejong
  email:             jessdejong843@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jessdejong/jessdejong.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
